### PR TITLE
Update the remoteprocess/proc-maps crates

### LINKED ISSUE #196: Function not implemented (os error 38)
I'm trying to use rbspy to record a process on a linux host (kernel 4.14.35). The process is a puma worker running a rails app. Its running in a docker container with the `SYS_PTRACE` capability enabled.

When I invoke `sudo ./rbspy record --format=summary --pid=$pid` I get 

```
Press Ctrl+C to stop
Wrote raw data to /root/.cache/rbspy/records/rbspy-2018-11-09-fVDwaLHJV5.raw.gz
Writing formatted output to /root/.cache/rbspy/records/rbspy-2018-11-09-hi93PXdZTo.summary.txt
Error. Causes:
- Couldn't determine Ruby version
- Couldn't create process handle for PID
- Failed to copy memory address 55e1929114bb
- Function not implemented (os error 38)
```

I'm ssh'd into the host and have root privs on the box. Any pointers on what to try next?

Thanks!

### PR DESCRIPTION
**Pull request by benfred**
The latest remoteprocess code includes a workaround for the case where the linux kernel
was compiled without process_vm_readv support (by falling back to /proc/PID/mem:
https://github.com/benfred/read-process-memory/pull/4).

Closes #196

### CODE REVIEW

**Comment by acj** [comment]
Thanks @benfred. I tried to do this upgrade the other day to fix a CI issue on Windows but didn't have time to sort out the type errors. Happy to work with you on this in whatever way makes sense.

**Comment by benfred** [comment]
Thanks @acj! 

The CI failures here were because we need https://github.com/rbspy/rbspy-testdata and https://github.com/rbspy/rbspy to use the exact same versions of remoteprocess in their Cargo.toml files. I've created a PR for the rbspy-testdata crate here: https://github.com/rbspy/rbspy-testdata/pull/4 which will also need merged

I've pointed this PR to link to my fork - which I'm hoping will sort out the CI failures 🤞

**Comment by acj** [comment]
Ahh, good to know. I don't have a commit bit for rbspy-testdata, but the changes LGTM both there and here.

The Travis musl build has been consistently failing recently, and we're planning to migrate that build to GH Actions soon, so it doesn't need to be a blocker imo.

**Review by acj — APPROVED** [review]

**Comment by jvns** [comment]
I merged the rbspy-testdata PR and gave both of you maintainer access on that repo

**Pull request merged**
