### PR TITLE
Add support for Ruby 2.5.4, 2.5.5, 2.6.0, 2.6.1, 2.6.2, 2.6.3

### LINKED ISSUE #207: Support for ruby 2.5.4 and 2.5.5
Looks like they are not supported yet.

### PR DESCRIPTION
**Pull request by neosilky**
This fixes #207 and #159.

Note: line numbers do not work correctly in 2.6.x. Several things changed in the internals and I can't figure out why my code doesn't work. Still, they're only a guide and the flamegraphs seem to be generated correctly otherwise so I figured it's probably better to get this pushed so people can use it.

### CODE REVIEW

**Comment by jvns** [comment]
Thanks so much for this! I added an issue about the line numbers in 2.6.x.

**Comment by kirs** [comment]
@neosilky do we need a new rbspy release to include this PR? The latest release seems to be from February: https://github.com/rbspy/rbspy/releases

**Comment by neosilky** [comment]
@kirs Yes. For the moment you can build rbspy using Rust. 

@jvns Would you be able to release a new version?

**Comment by jvns** [comment]
@neosilky the steps to release a new version are:

1. update `Cargo.toml` with the new version number & push a commit
2. add a git tag with the new version number & push the tags

the CI will automatically build a binary and add it to the github releases page

**Comment by neosilky** [comment]
@jvns Great, thanks!

**Comment by neosilky** [comment]
@kirs Check 0.3.6, just released :)

**Comment by kirs** [comment]
❤️ 💚 💛

**Pull request merged**
