### PR TITLE
[#189] Implement --subprocesses on Windows

### PR DESCRIPTION
**Pull request by akhramov**
Tracing subprocesses is not possible on Microsoft Windows, yet.

This change
* Implements `get_proc_children()` function for Windows, using
  `NtGetNextProcess` function. `NtGetNextProcess` is an undocumented
  routine of ntdll, but this approach is said to perform better than
  Process32First/Process32Next.
* Enables `--subprocesses` option for Windows.

### CODE REVIEW

**Comment by akhramov** [comment]
@jvns, this PR is ready for review.

I am sorry for the clumsy PR view -- had to force push a couple of times.
Also, the previous appveyor build stuck. Is there a way to cancel it?

There is no fork() in Windows' Ruby implementation, so I rewrote ` ci/ruby-programs/ruby_forks.rb` to use spawn() instead...

**Comment by akhramov** [comment]
Alright, let's hold it off a little bit. I need to get my hands on a real Windows machine to debug this.

**Comment by liaden** [comment]
I have a windows 10 box if you'd like me to try something.

**Comment by akhramov** [comment]
@liaden nope, thanks, I was going to download a windows VM anyway.

Technically, the solution should work -- I am wondering whether something is wrong with the CI machine.

**Comment by akhramov** [comment]
For some reason, I cannot reopen this request. I fixed the issue, though. Let's proceed in #224

**Pull request closed without merging**
