### PR TITLE
Add --silent flag, which allows to cancel every second logging

### PR DESCRIPTION
**Pull request by ViugiNick**
As we discussed in https://github.com/rbspy/rbspy/pull/199, sometimes it is needed to turn off the logging of the profiler's summary data.

P.S Can you please release the latest rpspy version, so we can share a link to it?

### CODE REVIEW

**Comment by ViugiNick** [comment]
@jvns Could you please take a look?

**Comment by jvns** [comment]
Thanks for the ping - this looks great.

**Comment by ViugiNick** [comment]
@jvns Thanks, it would be very nice to release a new version of the profiler.

**Comment by jvns** [comment]
i pushed a 0.3.5 tag which should do it.

**Comment by ViugiNick** [comment]
@jvns Could you please update homebrew too?

**Pull request merged**
