### PR TITLE
(ISSUE-257) Add 2.5.8 ruby version

### PR DESCRIPTION
**Pull request by donoghuc**
This commit adds support for ruby 2.5.8. Note there appear to be subtle differences between 2.5.7 and 2.5.8.

### CODE REVIEW

**Comment by donoghuc** [comment]
https://github.com/rbspy/rbspy/issues/257

**Comment by jvns** [comment]
did you test that this works with 2.5.8 on your machine?

**Comment by donoghuc** [comment]
Will add some notes about what i've done to test this.

**Comment by donoghuc** [comment]
Having some issues getting the tests to run. I installed `apt install musl musl-dev musl-tools` on bionic and get the following error:
```
root@easy-detachment:~/rbspy# TARGET=x86_64-unknown-linux-musl ./ci/script.sh 
+++ dirname ./ci/script.sh
++ . ./ci/utils.sh
++ main
++ run_test_suite
++ cargo build --target x86_64-unknown-linux-musl --verbose
       Fresh autocfg v0.1.7
   Compiling cfg-if v0.1.9
       Fresh semver-parser v0.7.0
   Compiling proc-macro2 v0.4.30
     Running `rustc --crate-name cfg_if /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.9/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=128120c6b057e4a2 -C extra-filename=-128120c6b057e4a2 --out-dir /root/rbspy/target/x86_64-unknown-linux-musl/debug/deps --target x86_64-unknown-linux-musl -L dependency=/root/rbspy/target/x86_64-unknown-linux-musl/debug/deps -L dependency=/root/rbspy/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.30/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=0abe2f3b67d9baed -C extra-filename=-0abe2f3b67d9baed --out-dir /root/rbspy/target/debug/build/proc-macro2-0abe2f3b67d9baed -L dependency=/root/rbspy/target/debug/deps --cap-lints allow`
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cfg_if /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.9/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=128120c6b057e4a2 -C extra-filename=-128120c6b057e4a2 --out-dir /root/rbspy/target/x86_64-unknown-linux-musl/debug/deps --target x86_64-unknown-linux-musl -L dependency=/root/rbspy/target/x86_64-unknown-linux-musl/debug/deps -L dependency=/root/rbspy/target/debug/deps --cap-lints allow` (exit code: 1)
```
My motivation for ruby 2.5.8 support was/is to profile a puma/sinatra app. This PR appears to work well for that ( i can get great profile data for the puma process).

**Comment by donoghuc** [comment]
I was wrong, there are some subtle differences between 2.5.7 and 2.5.8. I added some docs based on my expereince using the provided script to try to make it easier for people to do this. 

Here is the diff:
```diff
87d86
< pub type size_t = usize;
1919c1918
<     pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize], u8>,
---
>     pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize], u32>,
2131,2132c2130,2131
<     ) -> __BindgenBitfieldUnit<[u8; 8usize], u8> {
<         let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize], u8> =
---
>     ) -> __BindgenBitfieldUnit<[u8; 8usize], u32> {
>         let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize], u32> =
2519c2518
<     pub index: size_t,
---
>     pub index: usize,
4056c4055
<     pub living_thread_num: size_t,
---
>     pub living_thread_num: usize,
4152,4155c4151,4154
<     pub thread_vm_stack_size: size_t,
<     pub thread_machine_stack_size: size_t,
<     pub fiber_vm_stack_size: size_t,
<     pub fiber_machine_stack_size: size_t,
---
>     pub thread_vm_stack_size: usize,
>     pub thread_machine_stack_size: usize,
>     pub fiber_vm_stack_size: usize,
>     pub fiber_machine_stack_size: usize,
5112c5111
<     pub vm_stack_size: size_t,
---
>     pub vm_stack_size: usize,
5140c5139
<     pub stack_maxsize: size_t,
---
>     pub stack_maxsize: usize,
```

**Comment by donoghuc** [comment]
Could there be a race in the travis osx tests? The osx cell failed with:
```
failures:
---- test_spawn_record_children_subprocesses stdout ----
Press Ctrl+C to stop
thread 'test_spawn_record_children_subprocesses' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `4`', src/main.rs:496:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 
https://travis-ci.org/github/rbspy/rbspy/builds/694028138

I updated a commit that just reverted an accidental change to bindgen.sh and then it passed.

**Comment by jvns** [comment]
Thanks so much for those updates to the README -- huge improvement and long overdue :). I've noticed the flakiness in the tests before but haven't had time to track it down.

**Comment by jvns** [comment]
I made a new release `v0.3.10` with this commit so it should show up on on the releases page once the CI does its thing.

**Pull request merged**
